name: InfinityWarps
version: 0.0.1-SNAPSHOT
main: com.jstnf.infinitywarps.IWMain
author: jstnf-pokeball92870
description: A customizable, feature-packed warps plugin.

commands:
  infinitywarps:
    aliases: [iw]
    description: InfinityWarps main command
    permission: infinitywarps.infinitywarps
  warp:
    description: Warp to a location
    permission: infinitywarps.warp
  setwarp:
    description: Set a warp
    permission: infinitywarps.setwarp
  delwarp:
    description: Delete a warp
    permission: infinitywarps.delwarp
  warps:
    description: Open a menu to view all warps
    permission: infinitywarps.warps
  iwtest:
    description: Test various plugin functionality
    permission: infinitywarps.iwtest