#  ___       __ _      _ _      __      __
# |_ _|_ _  / _(_)_ _ (_) |_ _  \ \    / /_ _ _ _ _ __ ___  by jstnf
#  | || ' \|  _| | ' \| |  _| || \ \/\/ / _` | '_| '_ (_-<  Main Configuration File
# |___|_||_|_| |_|_||_|_|\__|\_, |\_/\_/\__,_|_| | .__/__/  config.yml
#                            |__/                |_|

infinitywarps:
  # Which locale should InfinityWarps use?
  locale: en_US
  # On teleport, should InfinityWarps center the player on the warp location block?
  center-on-block: true
  # Should InfinityWarps show the coordinates of a warp in the warp list and the warp GUI?
  show-coords: true

  item:
    border: BLACK_STAINED_GLASS_PANE
    # Default item in GUI when creating a warp
    warp: ENDER_PEARL
    # Default item in GUI when creating a warp group
    group: BOOK
