# +----------------------------------------------------+
# <                                                    >
# <        InfinityWarps by jstnf/pokeball92870        >
# <                 Configuration File                 >
# <                                                    >
# +----------------------------------------------------+

# Config Version (do not change this value!)
config-version: 1

# On teleport, should InfinityWarps center the player
# on the warp location block?
center-on-block: true

# Should InfinityWarps try to find a safe location
# to warp to?
# If false, InfinityWarps will warp the player
# directly to the location, regardless of safety.
# This includes in the air, in liquids, and inside of blocks.
safe-teleport: true

# By default, InfinityWarps will use this item as
# the warp item icon in the warps GUI.
# A complete list of possible items can be found at
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
default-warp-item: ENDER_PEARL
default-warp-group-item: BOOK

# Should players need a permission in order to use
# each warp?
# The permission required would be infinitywarps.warp.<warpname>
per-warp-permissions: false

# In seconds, the time before a warp is initiated.
# Warps are cancelled if the player moves at any time
# during this timer.
teleport-delay: 5

# In seconds, the cooldown timer between warps.
teleport-cooldown: 30

# Should InfinityWarps use the economy?
# This requires Vault as well as an economy plugin.
# If false, any costs associated to warps will not show
# up in menus or when using a warp.
use-economy: false

# What locale should InfinityWarps use?
locale: en_US

# Should the location of a warp
# be shown in the warp GUI and list?
show-coords: true

# Default items for the warps GUI.
border-item: LIGHT_BLUE_STAINED_GLASS_PANE
prev-page-item: FEATHER
next-page-item: FEATHER
