name: InfinityWarps
version: 0.0.1-dev
main: com.jstnf.infinitywarps.rewrite.InfinityWarps

author: jstnf-pokeball92870
description: A customizable, feature-packed warps plugin.

api-version: 1.13
softdepend: [Vault, Essentials]

commands:
  iw:
    aliases: [infinitywarps]
    description: The main command for InfinityWarps.
    permission: infinitywarps.infinitywarps
  setwarp:
    aliases: [isetwarp]
    description: Set a warp at your current location.
    permission: infinitywarps.setwarp
  warp:
    aliases: [iwarp]
    description: Teleport to a specified warp.
    permission: infinitywarps.warp
  iwdebuginv:
    description: Open a debug inventory for InfinityWarps.
    permission: infinitywarps.debuginv