name: InfinityWarps
version: ${version}
author: jstnf
main: dev.justinf.infinitywarps.InfinityWarps
api-version: 1.13

commands:
  iwdelwarp:
  iw:
  iwsetwarp:
  iwwarp:
  iwwarps:
  iwlistwarps:

permissions:
  infinitywarps.delwarp:
    description: Permission to remove a warp.
  infinitywarps.reload:
    description: Permission to reload InfinityWarps' config file and warps.
  infinitywarps.setwarp:
    description: Permission to set a warp.
