name: InfinityWarps
version: 0.0.1-dev
main: com.jstnf.infinitywarps.rewrite.IWMain

author: jstnf-pokeball92870
description: A customizable, feature-packed warps plugin.

api-version: 1.13
softdepend: [Vault, Essentials]

commands:
  iw:
    aliases: [infinitywarps]
    description: The main command for InfinityWarps.
    permission: infinitywarps.infinitywarps