package com.jstnf.infinitywarps.rewrite.commands.iw;

import com.jstnf.infinitywarps.rewrite.settings.IWLocale;

/**
 * Enum that contains constants for JSON components in /iw help
 *
 * @author jstnf
 * 18 May 2019
 */
public enum HelpEntry
{
	IW(IWLocale.HELP_COMMANDS_IW, IWLocale.HELP_DESCRIPTION_IW, false, ""),
	IW_HELP(IWLocale.HELP_COMMANDS_IW_HELP, IWLocale.HELP_DESCRIPTION_IW_HELP, true, "/iw help "),
	IW_IMPORTESSWARPS(IWLocale.HELP_COMMANDS_IW_IMPORTESSWARPS, IWLocale.HELP_DESCRIPTION_IW_IMPORTESSWARPS, false, ""),
	IW_RELOAD(IWLocale.HELP_COMMANDS_IW_RELOAD, IWLocale.HELP_DESCRIPTION_IW_RELOAD, false, ""),
	DELWARP(IWLocale.HELP_COMMANDS_DELWARP, IWLocale.HELP_DESCRIPTION_DELWARP, true, "/delwarp "),
	EDITWARP_INFO(IWLocale.HELP_COMMANDS_EDITWARP_INFO, IWLocale.HELP_DESCRIPTION_EDITWARP_INFO, false, ""),
	EDITWARP_LORE_ADD(IWLocale.HELP_COMMANDS_EDITWARP_LORE_ADD, IWLocale.HELP_DESCRIPTION_EDITWARP_LORE_ADD, false, ""),
	EDITWARP_LORE_EDIT(IWLocale.HELP_COMMANDS_EDITWARP_LORE_EDIT, IWLocale.HELP_DESCRIPTION_EDITWARP_LORE_EDIT, false, ""),
	EDITWARP_LORE_LIST(IWLocale.HELP_COMMANDS_EDITWARP_LORE_LIST, IWLocale.HELP_DESCRIPTION_EDITWARP_LORE_LIST, false, ""),
	EDITWARP_LORE_REMOVE(IWLocale.HELP_COMMANDS_EDITWARP_LORE_REMOVE, IWLocale.HELP_DESCRIPTION_EDITWARP_LORE_REMOVE, false, ""),
	EDITWARP_RENAME(IWLocale.HELP_COMMANDS_EDITWARP_RENAME, IWLocale.HELP_DESCRIPTION_EDITWARP_RENAME, false, ""),
	EDITWARP_SETITEM(IWLocale.HELP_COMMANDS_EDITWARP_SETITEM, IWLocale.HELP_DESCRIPTION_EDITWARP_SETITEM, false, ""),
	SETWARP(IWLocale.HELP_COMMANDS_SETWARP, IWLocale.HELP_DESCRIPTION_SETWARP, true, "/setwarp "),
	WARP(IWLocale.HELP_COMMANDS_WARP, IWLocale.HELP_DESCRIPTION_WARP, true, "/warp "),
	WARPGROUP_ADD(IWLocale.HELP_COMMANDS_WARPGROUP_ADD, IWLocale.HELP_DESCRIPTION_WARPGROUP_ADD, true, "/warpgroup add "),
	WARPGROUP_ADDWARP(IWLocale.HELP_COMMANDS_WARPGROUP_ADDWARP, IWLocale.HELP_DESCRIPTION_WARPGROUP_ADDWARP, false, ""),
	WARPGROUP_INFO(IWLocale.HELP_COMMANDS_WARPGROUP_INFO, IWLocale.HELP_DESCRIPTION_WARPGROUP_INFO, false, ""),
	WARPGROUP_LIST(IWLocale.HELP_COMMANDS_WARPGROUP_LIST, IWLocale.HELP_DESCRIPTION_WARPGROUP_LIST, true, "/warpgroup list "),
	WARPGROUP_LORE_ADD(IWLocale.HELP_COMMANDS_WARPGROUP_LORE_ADD, IWLocale.HELP_DESCRIPTION_WARPGROUP_LORE_ADD, false, ""),
	WARPGROUP_LORE_EDIT(IWLocale.HELP_COMMANDS_WARPGROUP_LORE_EDIT, IWLocale.HELP_DESCRIPTION_WARPGROUP_LORE_EDIT, false, ""),
	WARPGROUP_LORE_LIST(IWLocale.HELP_COMMANDS_WARPGROUP_LORE_LIST, IWLocale.HELP_DESCRIPTION_WARPGROUP_LORE_LIST, false, ""),
	WARPGROUP_LORE_REMOVE(IWLocale.HELP_COMMANDS_WARPGROUP_LORE_REMOVE, IWLocale.HELP_DESCRIPTION_WARPGROUP_LORE_REMOVE, false, ""),
	WARPGROUP_REMOVE(IWLocale.HELP_COMMANDS_WARPGROUP_REMOVE, IWLocale.HELP_DESCRIPTION_WARPGROUP_REMOVE, true, "/warpgroup remove "),
	WARPGROUP_REMOVEWARP(IWLocale.HELP_COMMANDS_WARPGROUP_REMOVEWARP, IWLocale.HELP_DESCRIPTION_WARPGROUP_REMOVEWARP, false, ""),
	WARPGROUP_RENAME(IWLocale.HELP_COMMANDS_WARPGROUP_RENAME, IWLocale.HELP_DESCRIPTION_WARPGROUP_RENAME, false, ""),
	WARPGROUP_SETITEM(IWLocale.HELP_COMMANDS_WARPGROUP_SETITEM, IWLocale.HELP_DESCRIPTION_WARPGROUP_SETITEM, false, ""),
	WARPLIST(IWLocale.HELP_COMMANDS_WARPLIST, IWLocale.HELP_DESCRIPTION_WARPLIST, true, "/warplist "),
	WARPMENU(IWLocale.HELP_COMMANDS_WARPMENU, IWLocale.HELP_DESCRIPTION_WARPMENU, false, "");

	private IWLocale command, description;
	private boolean useCustomSuggestion;
	private String customSuggestion;

	HelpEntry(IWLocale command, IWLocale description, boolean useCustomSuggestion, String customSuggestion)
	{
		this.command = command;
		this.description = description;
		this.useCustomSuggestion = useCustomSuggestion;
		this.customSuggestion = customSuggestion;
	}

	public IWLocale command()
	{
		return command;
	}

	public IWLocale description()
	{
		return description;
	}

	public String suggestion()
	{
		if (useCustomSuggestion)
		{
			return customSuggestion;
		}
		else
		{
			return (String) command.getDefaultValue();
		}
	}
}